---
title: Workshop
description: A two-week hands-on workshop aiming to formalize more basic polyhedra theory
keywords: polytopes, polyhedra, lean, formalization, workshop

extensions:
  - typography
  - fences
  - embed
  - highlighting
