---
title: Workshop
description: A two-week hands-on workshop aiming to formalize more basic polytope theory
keywords: polytopes, lean, formalization, workshop

extensions:
  - typography
  - fences
  - embed
  - highlighting
